substitutions:
  devicename: dehumidifier-taiseia-s3
  upper_devicename: "Dehumidifier"

esphome:
  name: $devicename
  friendly_name: ${upper_devicename}
  comment: $upper_devicename faikin for RD-240HH
#  name_add_mac_suffix: true
  project:
    name: TaiSEIA.dehumidifier
    version: "faikin-s3-1.0"
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
  on_boot:
    priority: 600
    then:
      - lambda: |-
          gpio_set_pull_mode(GPIO_NUM_34, GPIO_PULLUP_ONLY);

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
    version: 2.0.6

external_components:
  - source: github://tsunglung/taixia@master
    components: [ taixia ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename}
    password: "12345678"

# Enable logging
logger:
  baud_rate: 0 # disable serial logging;
#  level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:

uart:
  id: uart_taixia
  tx_pin: 
    number: GPIO48
    inverted: true
  rx_pin: 
    number: GPIO34
    inverted: true
  baud_rate: 9600
  debug:
    direction: BOTH

# optional binary sensor to monitor serial connection:
binary_sensor:
  - platform: status
    name: "Status"
  - platform: taixia
    type: dehumidifier
    water_tank_full:
      name: "Water Tank Full"
    filter_notify:
      name: "Filter Notify"
    side_air_flow:
      name: "Side Air Flow"
    defrost:
      name: "Defrost"
    odours:
      name: "Odours"

button:
  - platform: safe_mode
    name: "Safe Mode Boot"
    entity_category: diagnostic
  - platform: restart
    name: "Restart"
  - platform: taixia
    type: dehumidifier
    get_info:
      name: "Get Info"

fan:
  - platform: taixia
    name: Fan
    type: dehumidifier
    id: fan_dehumidifier
    speed: true
    speed_count: 4
    preset_modes:
#      - auto
      - normal
      - home
      - boost
#      - home
      - sleep
#      - fan
#      - comfort
#      - away
      - eco

interval:
  - interval: 60s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - light.turn_off:
              id: s3_wled
        else:
          - light.turn_on:
              id: s3_wled
              flash_length : 1s

light:
  - platform: esp32_rmt_led_strip
    chipset: WS2812
    pin: GPIO47
    num_leds: 3
    rgb_order: GRB
    rmt_channel: 0
    id: s3_wled
    name: "RGB LED"

number:
  - platform: taixia
    type: dehumidifier
    operating_time:
      name: "Operating Time"
    relative_humidity:
      name: "Relative Humidity"
#    dehumidifier_level:
#      name: "Dehumidifier Level"
#    dry_level:
#      name: "Dry Level"
#    fan_angle:
#      name: "Fan Angle"
#    air_purifier:
#      name: "Air Purifier"
#    fan_level:
#      name: "Fan Level"
    sound_mode:
      name: "Sound Mode"
#    high_humidity_level:
#      name: "High Humidity Level"
    light_level:
      name: "Light Level"

select:
  - platform: taixia
    type: dehumidifier
    operating_program:
      name: "Operation Mode"
      options:
        - normal
        - eco
        - home
        - boost
        - sleep

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1

  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: taixia
    type: dehumidifier
    humidity_indoor:
      name: "Humidity Indoor"
      on_value_range:
        - below: 40
          then:
            - lambda: |-
                // Set a preset mode
                auto call = id(fan_dehumidifier).turn_on();
                call.set_preset_mode("eco");
                call.perform();
        - above: 80
          then:
            - lambda: |-
                // Set a preset mode
                auto call = id(fan_dehumidifier).turn_on();
                call.set_preset_mode("boost");
                call.perform();
    energy_consumption:
      name: "Energy"
    error_code:
      name: "Error Code"
    pm_2_5:
      name: "PM 2.5"

switch:
  - platform: taixia
    type: dehumidifier
    power:
      name: "Power Switch"
    lock:
      name: "Lock"
    air_flow_auto:
      name: "Auto Air Flow"
    mildew_proof:
      name: "Mildew Proof"
    humidity_notify:
      name: "Humidity Notify"
#    light:
#      name: "Light"
    beeper:
      name: "Beeper"
    air_purifier:
      name: "Air Purifier"
#    filter_reset:
#      name: "Filter Reset"
    pm25_detect:
      name: "PM2.5 Detect"

text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
  - platform: taixia
    sa_id:
      name: "SA ID"
      id: sa_id
    brand:
      name: "SA Brand"
    model:
      name: "SA Model"
    version:
      name: "SA Version"
    services:
      name: "SA Services"

taixia:
  sa_id: 4
#  response_time: 0

time:
  - platform: homeassistant
    id: homeassistant_time
